export const PRACTICE_AREAS = [
  { value: 'driver', label: 'Driver' },
  { value: 'irons', label: 'Irons' },
  { value: 'wedges', label: 'Wedges' },
  { value: 'putting', label: 'Putting' },
];

export const PRACTICE_DRILLS = {
  driver: [
    {
      title: 'Fairway Ladder',
      setup: 'Pick a fairway-width target between two range markers.',
      instructions: 'Hit 10 drives. Start with a smooth fairway finder, then add speed only after two target hits in a row.',
      score: 'Count target hits out of 10. Goal: 6 or more.',
      resultLabel: 'target hits',
      attempts: 10,
      goal: 6,
    },
    {
      title: 'Nine-Shot Start Line',
      setup: 'Choose one start line and one landing window.',
      instructions: 'Hit three fades, three straight balls, and three draws. Commit to the start line before each swing.',
      score: 'Count shots that started on the intended line.',
      resultLabel: 'start-line hits',
      attempts: 9,
      goal: 6,
    },
    {
      title: 'Pressure Tee Ball',
      setup: 'Imagine a tight opening hole with trouble on one side.',
      instructions: 'Hit 12 drives using your full routine. Restart the count whenever you miss two in a row.',
      score: 'Goal: finish with 8 playable tee balls.',
      resultLabel: 'playable tee balls',
      attempts: 12,
      goal: 8,
    },
    {
      title: 'Two-Sided Miss Test',
      setup: 'Pick a center target and mark a left boundary and right boundary.',
      instructions: 'Hit 14 drives. A ball counts if it finishes inside the boundaries and would be playable from a normal hole.',
      score: 'Count playable drives out of 14. Goal: 9 or more.',
      resultLabel: 'playable drives',
      attempts: 14,
      goal: 9,
    },
    {
      title: 'Fairway Finder Reps',
      setup: 'Choose your safest tee shot shape and a fairway-width target.',
      instructions: 'Hit 10 controlled drives at 80-90% speed. Use the same routine and same shot shape every time.',
      score: 'Count drives that start online and finish playable. Goal: 7 or more.',
      resultLabel: 'fairway finders',
      attempts: 10,
      goal: 7,
    },
    {
      title: 'Speed Then Control',
      setup: 'Pick one wide target window.',
      instructions: 'Hit five hard drives, then five controlled drives. The goal is to keep speed without losing the playable window.',
      score: 'Count playable drives out of 10. Goal: 6 or more.',
      resultLabel: 'playable drives',
      attempts: 10,
      goal: 6,
    },
    {
      title: 'Start-Line Gate',
      setup: 'Use two range markers or imagined posts about 10 yards apart as a starting gate.',
      instructions: 'Hit 12 drives. Only count shots that launch through the starting gate, regardless of final curve.',
      score: 'Count start-line hits out of 12. Goal: 8 or more.',
      resultLabel: 'start-line hits',
      attempts: 12,
      goal: 8,
    },
    {
      title: 'Simulated Driving Holes',
      setup: 'Create six imaginary holes with different fairway shapes.',
      instructions: 'Play two drives per hole. Pick the club, shot shape, and target before every ball.',
      score: 'Count drives that would leave a clear approach. Goal: 8 out of 12.',
      resultLabel: 'clear approaches',
      attempts: 12,
      goal: 8,
    },
  ],
  irons: [
    {
      title: 'Three-Club Windows',
      setup: 'Pick one target and use three different clubs.',
      instructions: 'Hit five balls with each club, trying to land each inside the same target window with different trajectories.',
      score: 'Count balls finishing in the window out of 15.',
      resultLabel: 'window hits',
      attempts: 15,
      goal: 9,
    },
    {
      title: 'Green Light, Yellow Light',
      setup: 'Pick a target green or range landing zone.',
      instructions: 'Hit 12 approach shots. Before each one, call the miss you can accept and the miss you cannot.',
      score: 'Count shots with acceptable misses.',
      resultLabel: 'acceptable results',
      attempts: 12,
      goal: 8,
    },
    {
      title: 'Random Approach Bag',
      setup: 'Use four clubs: short iron, mid iron, long iron or hybrid, and wedge.',
      instructions: 'Change clubs every ball. Pick a new target each time and go through your full routine.',
      score: 'Count solid strikes plus target-zone finishes.',
      resultLabel: 'target approaches',
      attempts: 16,
      goal: 10,
    },
    {
      title: 'Nine-Ball Trajectory',
      setup: 'Pick one target and one mid iron.',
      instructions: 'Hit three low, three stock, and three high shots. Call the trajectory before each swing.',
      score: 'Count shots with the intended trajectory and solid contact. Goal: 6 out of 9.',
      resultLabel: 'trajectory hits',
      attempts: 9,
      goal: 6,
    },
    {
      title: 'GIR Simulator',
      setup: 'Pick 10 different approach targets between short and mid iron range.',
      instructions: 'Treat every ball like an approach into a green. Change target and club often.',
      score: 'Count shots that would finish on a green-sized target. Goal: 6 out of 10.',
      resultLabel: 'greens hit',
      attempts: 10,
      goal: 6,
    },
    {
      title: 'Contact First',
      setup: 'Use one iron and a small target. Focus on strike before direction.',
      instructions: 'Hit 15 balls. Count only shots with clean contact and balanced finish.',
      score: 'Count clean strikes out of 15. Goal: 11 or more.',
      resultLabel: 'clean strikes',
      attempts: 15,
      goal: 11,
    },
    {
      title: 'Distance Ladder',
      setup: 'Pick one club and three distances: short, stock, and smooth hard.',
      instructions: 'Hit four balls to each distance without changing clubs. Control swing length and tempo.',
      score: 'Count shots that finish near the intended distance. Goal: 8 out of 12.',
      resultLabel: 'distance hits',
      attempts: 12,
      goal: 8,
    },
    {
      title: 'One-Shot Challenge',
      setup: 'Pick 12 targets and allow only one ball per target.',
      instructions: 'Go through a full routine, hit one shot, then move on. No do-overs.',
      score: 'Count acceptable approach results. Goal: 7 out of 12.',
      resultLabel: 'acceptable shots',
      attempts: 12,
      goal: 7,
    },
  ],
  wedges: [
    {
      title: '30-50-70 Ladder',
      setup: 'Pick three wedge distances: 30, 50, and 70 yards.',
      instructions: 'Hit three balls to each distance, then repeat in reverse order. Change targets every three balls.',
      score: 'Count balls inside a comfortable two-putt circle.',
      resultLabel: 'inside circle',
      attempts: 18,
      goal: 10,
    },
    {
      title: 'Up-and-Down Circuit',
      setup: 'Create nine short-game lies around a green or practice area.',
      instructions: 'Play each ball out until holed. Use your real pre-shot routine and vary trajectory.',
      score: 'Goal: 4 up-and-downs out of 9.',
      resultLabel: 'up-and-downs',
      attempts: 9,
      goal: 4,
    },
    {
      title: 'Landing Spot Challenge',
      setup: 'Place a towel or pick a landing patch.',
      instructions: 'Hit 20 chips or pitches trying to land the ball on the spot, not just near the hole.',
      score: 'Count landing spot hits out of 20.',
      resultLabel: 'landing spot hits',
      attempts: 20,
      goal: 10,
    },
    {
      title: 'Par-18 Short Game',
      setup: 'Choose nine different chip or pitch shots around a green.',
      instructions: 'Play each ball until holed. Par is two strokes per station.',
      score: 'Count stations completed in two strokes or better. Goal: 5 out of 9.',
      resultLabel: 'pars or better',
      attempts: 9,
      goal: 5,
    },
    {
      title: 'Three-Trajectory Wedges',
      setup: 'Pick one distance and three trajectories: low, medium, high.',
      instructions: 'Hit four balls with each trajectory. Call the flight before swinging.',
      score: 'Count shots with the intended flight and playable distance. Goal: 8 out of 12.',
      resultLabel: 'flighted wedges',
      attempts: 12,
      goal: 8,
    },
    {
      title: 'Ten-Yard Windows',
      setup: 'Pick wedge targets at 40, 50, 60, and 70 yards.',
      instructions: 'Hit three balls to each target. A ball counts if it finishes inside a 10-yard depth window.',
      score: 'Count distance-window hits out of 12. Goal: 7 or more.',
      resultLabel: 'window hits',
      attempts: 12,
      goal: 7,
    },
    {
      title: 'Bunker Up-and-Down',
      setup: 'Use a practice bunker or simulate bunker shots if one is not available.',
      instructions: 'Play 10 balls toward a hole or target. Count shots that finish inside a reasonable makeable putt range.',
      score: 'Count bunker saves or close finishes out of 10. Goal: 5 or more.',
      resultLabel: 'bunker saves',
      attempts: 10,
      goal: 5,
    },
    {
      title: 'One-Ball Scramble',
      setup: 'Drop one ball in 10 different short-game spots.',
      instructions: 'Play each shot with full routine. No second chances from the same lie.',
      score: 'Count shots that finish inside a three-foot circle or are holed. Goal: 5 out of 10.',
      resultLabel: 'inside 3 feet',
      attempts: 10,
      goal: 5,
    },
  ],
  putting: [
    {
      title: 'Clock Drill',
      setup: 'Place balls at 3, 4, and 5 feet around the hole.',
      instructions: 'Work around the hole. Make every putt at one distance before moving back.',
      score: 'Goal: complete the full clock with no more than two misses.',
      resultLabel: 'made putts',
      attempts: 12,
      goal: 10,
    },
    {
      title: 'Lag Ladder',
      setup: 'Pick putts from 20, 30, 40, and 50 feet.',
      instructions: 'Hit three putts from each distance. The only goal is speed control.',
      score: 'Count balls finishing inside a three-foot circle.',
      resultLabel: 'inside 3 feet',
      attempts: 12,
      goal: 9,
    },
    {
      title: 'Make-Rate Test',
      setup: 'Set 10 putts from 4 feet, 10 from 6 feet, and 10 from 8 feet.',
      instructions: 'Go through your full routine on every putt. Reset after each distance.',
      score: 'Track makes out of 30.',
      resultLabel: 'made putts',
      attempts: 30,
      goal: 18,
    },
    {
      title: 'Three-Foot Circle',
      setup: 'Place 12 balls around the hole from three feet.',
      instructions: 'Work around the circle. Use your full routine and do not rake misses back.',
      score: 'Count makes out of 12. Goal: 10 or more.',
      resultLabel: 'made putts',
      attempts: 12,
      goal: 10,
    },
    {
      title: 'Gate Start Line',
      setup: 'Place two tees just wider than your putter head about one foot in front of the ball.',
      instructions: 'Hit 15 putts through the gate from 5-8 feet. Count only putts that start through the gate.',
      score: 'Count gate starts out of 15. Goal: 12 or more.',
      resultLabel: 'gate starts',
      attempts: 15,
      goal: 12,
    },
    {
      title: 'Around the World',
      setup: 'Place eight balls in a circle around the hole from 4-6 feet.',
      instructions: 'Putt each ball once. Move around the circle and read every putt individually.',
      score: 'Count makes out of 8. Goal: 6 or more.',
      resultLabel: 'made putts',
      attempts: 8,
      goal: 6,
    },
    {
      title: 'Speed Ladder',
      setup: 'Pick putts from 15, 25, 35, 45, and 55 feet.',
      instructions: 'Hit two putts from each distance. The target is speed control, not making them.',
      score: 'Count putts finishing inside three feet. Goal: 7 out of 10.',
      resultLabel: 'inside 3 feet',
      attempts: 10,
      goal: 7,
    },
    {
      title: 'Consecutive Short Putts',
      setup: 'Pick a straight 4-foot putt.',
      instructions: 'Try to make 20 in a row. If you miss, keep going until all 20 attempts are complete.',
      score: 'Count makes out of 20. Goal: 18 or more.',
      resultLabel: 'made putts',
      attempts: 20,
      goal: 18,
    },
  ],
};

function requireMeasurableGoal(drill) {
  if (!drill?.resultLabel || drill.attempts == null || drill.goal == null) {
    throw new Error(`Practice drill "${drill?.title ?? 'unknown'}" is missing a measurable goal.`);
  }
  return drill;
}

export function getRandomDrill(area, previousTitle) {
  const drills = PRACTICE_DRILLS[area] ?? PRACTICE_DRILLS.driver;
  const available = drills.length > 1
    ? drills.filter((drill) => drill.title !== previousTitle)
    : drills;
  return requireMeasurableGoal(available[Math.floor(Math.random() * available.length)]);
}
